version: '3'

services:
  nodejs:
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    container_name: nodejs
    restart: always
    ports:
        - "3000:3000" 
    networks:
        - nodenetwork  

  mongo:
    container_name: mongo
    image: mongo
    volumes:
        - mongovolume:/data/db
    networks:
        - mongonetwork
  
  frontend:
    build: 
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
        - "8000:8000"
    networks:
        - frontendnetwork

volumes:
  mongovolume:

networks:
  mongonetwork:
  nodenetwork:
  frontendnetwork:

